os: osx
language: c++

addons:
  homebrew:
    packages:
    - libmad
    - libpng
    - jpeg-turbo
    - sdl2
    - pango

before_install:
  - brew update
  - brew bundle
  - brew uninstall libjpeg --ignore-dependencies # wrong libjpeg version can cause us problems
script: 
  - xcodebuild
  - cd build/Release/EndlessSky.app/Contents/MacOS/
  - install_name_tool -change /usr/local/opt/libpng/lib/libpng16.16.dylib @executable_path/../Frameworks/libpng16.16.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/mad/lib/libmad.0.dylib @executable_path/../Frameworks/libmad.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib @executable_path/../Frameworks/libSDL2-2.0.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/jpeg-turbo/lib/libturbojpeg.0.dylib @executable_path/../Frameworks/libturbojpeg.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/pango/1.42.4/lib/libpango-1.0.0.dylib @executable_path/../Frameworks/libpango-1.0.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/pango/1.42.4/lib/libpangocairo-1.0.0.dylib @executable_path/../Frameworks/libpangocairo-1.0.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/glib/2.58.2/lib/libglib-2.0.0.dylib @executable_path/../Frameworks/libglib-2.0.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/fontconfig/2.13.1/lib/libfontconfig.1.dylib @executable_path/../Frameworks/libfontconfig.1.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/glib/2.58.2/lib/libgobject-2.0.0.dylib @executable_path/../Frameworks/libgobject-2.0.0.dylib EndlessSky
  - install_name_tool -change /usr/local/opt/cairo/1.16.0/lib/libcairo.2.dylib @executable_path/../Frameworks/libcairo.2.dylib EndlessSky
